# Generated by Django 4.2.1 on 2023-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_1',
            name='number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
