# Generated by Django 4.2.1 on 2023-06-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_form_1_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_1',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
