# Generated by Django 4.2.1 on 2023-06-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0003_form_1_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_1',
            name='state',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
