# Generated by Django 4.2.1 on 2023-06-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0005_form_1_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_1',
            name='bool',
        ),
    ]
