# Generated by Django 4.2.1 on 2023-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0007_alter_form_1_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=18)),
                ('state', models.CharField(max_length=20)),
                ('permission', models.CharField(max_length=3)),
            ],
        ),
    ]
