# Generated by Django 4.2.1 on 2023-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0009_form_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='verification0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_choisi', models.CharField(db_column='jour_choisi', max_length=9)),
            ],
        ),
    ]
