# Generated by Django 4.2.1 on 2023-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0012_form_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_3',
            name='dix_heure',
            field=models.CharField(db_column='dix_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='dix_huit_heure',
            field=models.CharField(db_column='dix_huit_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='dix_neuf_heure',
            field=models.CharField(db_column='dix_neuf_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='dix_sept_heure',
            field=models.CharField(db_column='dix_sept_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='douze_heure',
            field=models.CharField(db_column='douze_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='huit_heure',
            field=models.CharField(db_column='huit_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='jour',
            field=models.CharField(db_column='jour', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='neuf_heure',
            field=models.CharField(db_column='neuf_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='onze_heure',
            field=models.CharField(db_column='onze_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='quatorze_heure',
            field=models.CharField(db_column='quatorze_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='quinze_heure',
            field=models.CharField(db_column='quinze_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='seize_heure',
            field=models.CharField(db_column='seize_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='sept_heure',
            field=models.CharField(db_column='sept_heure', max_length=2),
        ),
        migrations.AlterField(
            model_name='form_3',
            name='treize_heure',
            field=models.CharField(db_column='treize_heure', max_length=2),
        ),
    ]
