# Generated by Django 4.2.1 on 2023-06-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0014_alter_form_3_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_3',
            name='nom',
            field=models.CharField(db_column='nom', default=0, max_length=100),
            preserve_default=False,
        ),
    ]
