# Generated by Django 4.2.1 on 2023-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0016_alter_form_1_email_alter_form_2_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_5',
            name='occupation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
