# Generated by Django 4.2.1 on 2023-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0017_form_5_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_5',
            name='occupation',
            field=models.IntegerField(db_column="Occupé ( 0 pour 'non'  et   1 pour 'oui' )"),
        ),
    ]
