# Generated by Django 4.2.1 on 2023-06-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0018_alter_form_5_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_5',
            name='occupation',
            field=models.CharField(db_column="Occupé ( 0 pour 'non'  et   1 pour 'oui' )", max_length=1),
        ),
    ]
