# Generated by Django 4.2.1 on 2023-06-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0020_alter_form_5_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_5',
            name='occupation',
        ),
        migrations.AddField(
            model_name='form_5',
            name='occupate',
            field=models.CharField(db_column='occupate', default=0, max_length=1),
            preserve_default=False,
        ),
    ]
